name: Build and Release
on:
  push:
    branches:
      - dev
      - main
    paths:
      - "vminfo_parser/*"
      - "pyproject.toml"
      - "MANIFEST.in"
      - "requirements.txt"

permissions:
  checks: write
  contents: write
  packages: write

jobs:
  release:
    name: Python Semantic Release
    runs-on: ubuntu-latest
    steps:
      # Note: we need to checkout the repository at the workflow sha in case during the workflow
      # the branch was updated. To keep PSR working with the configured release branches,
      # we force a checkout of the desired release branch but at the workflow sha HEAD.
      - name: Setup | Checkout Repository at workflow sha
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}

      - name: Setup | Force correct release branch on workflow sha
        run: |
          git checkout -B ${{ github.ref_name }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@v9
        with:
          github_token: ${{ github.token }}
          changelog: false
          prerelease: ${{ github.ref_name != 'main' }}
          commit: ${{ github.ref_name == 'main' }}
