name: Build and Release
on:
  push:
    branches:
      - dev
      - main
    paths:
      - "vminfo_parser/*"
      - "pyproject.toml"
      - "MANIFEST.in"
      - "requirements.txt"

permissions:
  checks: write
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Python Semantic Release
        id: release
        uses: ./
        with:
          github_token: ${{ github.token }}
          changelog: false
          prerelease: ${{ github.ref_name != 'main' }}
          commit: ${{ github.ref_name == 'main' }}
